-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/fZnX3JwgDX4RCvO
2qxgYREXMLN44EzsVOtZBLLklHOgCgYIKoZIzj0DAQehRANCAAQl9Skw1JTfH6i9
PmsUBmqZbiTjnX/B6IffDglJTj3Xa6J8mwjKOsVwg/CdeouHD0O82q0Gs9gDCqOa
N14/Klgz
-----END PRIVATE KEY-----
